name: Pull & Run
on:
  push:
    branches:
      - sveltepage

jobs:
    run_pull:
      name: run pull
      runs-on: ubuntu-latest

      steps:
      - name: Starting workflow
        run: echo "Starting workflow"
        
      - name: Install SSH keys
        run:
          echo "Installing SSH keys"
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          
      - name: Pulling Changes
        run:
          echo "Pulling Changes"
          cd ${{ secrets.WORK_DIR }} && git pull origin sveltepage
        
      - name: Starting npm dev server
        run: echo "Starting npm dev server"
        
      - name: Start npm dev server
        run:
          npm run dev -- --host

      - name: cleanup
        run: rm -rf ~/.ssh
