name: Pull & Run
on:
  push:
    branches:
      - sveltepage
jobs:
    run_pull:
      name: run pull
      runs-on: ubuntu-latest

      steps:
      - name: Starting workflow
        run: echo "Starting workflow"
            
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: sveltepage

      - name: WHERE AM I?
        run: pwd && echo ls -al *

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Remove existing install
        run: rm -rf node_modules package-lock.json

      - name: Clear NPM Cache
        run: npm cache clean --force

      - name: Reinstall Packages
        run: npm install

      - name: Install Svelte Eslint
        run: npm install --save-dev eslint eslint-plugin-svelte svelte
      
      - name: Run ESLint on Components
        run: npx eslint src/components/*

      - name: Run ESLint on Routes
        run: npx eslint src/routes/*

      
