name: Pull & Run
on:
  push:
    branches:
      - sveltepage
jobs:
    run_pull:
      name: run pull
      runs-on: ubuntu-latest

      steps:
      - name: Starting workflow
        run: echo "Starting workflow"
        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      
      - name: Install npm
        run: npm install

      - name: Run ESLint
        run: npx lint .

      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
          
      - name: Pulling Changes
        run:
          echo "Pulling Changes"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull origin sveltepage && npm run dev -- --host"

      - name: cleanup
        run: rm -rf ~/.ssh
